server:
  port: 8092

spring:
  application:
    name: demo-app
    version: 1.2.0

exception:
  handler:
    project-name: demo-application
    component-name: demo-app
    pod-name: demo-pod-001
    pod-ip: 192.168.1.100
    cluster-name: development-cluster
    environment: UAT
    kafka:
      topic: exceptions
      bootstrap-servers: localhost:9092
    
logging:
  level:
    com.example.demo: DEBUG
    com.example.exception.handler: DEBUG
    org.springframework.kafka: INFO